FROM alpine:3.18@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:6a76e13f1f4a22a6836189b9828e3de64cddae418ff5a15f10715a596ccc08a5

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
